name: Build MultiMC Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p multimc/.minecraft
          cp -r instance.cfg multimc
          cp -r mmc-pack.json multimc
          cp -r mods multimc/.minecraft
          cp -r config multimc/.minecraft
          cp -r options.txt multimc/.minecraft
      - run: zip -r multimc.zip multimc
      - uses: actions/upload-artifact@v3
        with:
          path: multimc.zip
